autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

frontend:
  replicaCount: 3
  image:
    tag: "alpine"
  service:
    nodePort: 30003

active:
  nodePort: 30093

backend:
  replicaCount: 3

database:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"