apiVersion: v1
kind: Secret
metadata:
  name: {{ include "three-tier-app.fullname" . }}-database-secret
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}
    app: database
type: Opaque
data:
  root-password: {{ .Values.database.auth.rootPassword | b64enc | quote }}
  db-password: {{ .Values.database.auth.password | b64enc | quote }}
