apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "three-tier-app.fullname" . }}-database-pvc
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
