apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "three-tier-app.fullname" . }}-frontend
  labels:
    {{- include "three-tier-app.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        release: {{ .Release.Name }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
